#!/bin/sh

if ! MYTMP="`mktemp -d -t install-iprange-XXXXXX`"
then
            echo >&2
            echo >&2
            echo >&2 "Cannot create temporary directory."
            echo >&2
            exit 1
fi
export MYTMP

myexit() {
  rm -rf $MYTMP
  exit 0
}

trap myexit INT
trap myexit HUP
trap myexit 0

DIR=`pwd`/
export DIR

cd $MYTMP

set -e

curl -s -o json https://api.github.com/repos/firehol/iprange/releases/latest
dl=$(sed -ne '/"browser_download_url":.*.tar.gz"/{s/.*"browser_download_url": *//;s/{.*//;s/",*//g;p;q}' json)
dl=https://github.com/firehol/iprange/releases/download/v1.0.4/iprange-1.0.4.tar.gz

if [ "$dl" = "" ]
then
  echo "Could not find download for latest iprange"
  exit 1
fi

curl -s -L -o iprange.tar.gz "$dl"
if [ $? -ne 0 ]
then
  echo "Could not download $dl"
  exit 1
else
  echo "Building $dl"
fi

mkdir build
tar xfzC iprange.tar.gz build

cd build/iprange*
./configure --disable-man
make install
