#!/bin/sh

if ! MYTMP="`mktemp -d -t replace-unshare-XXXXXX`"
then
            echo >&2
            echo >&2
            echo >&2 "Cannot create temporary directory."
            echo >&2
            exit 1
fi
export MYTMP

myexit() {
  rm -rf $MYTMP
  exit 0
}

trap myexit INT
trap myexit HUP
trap myexit 0

DIR=`pwd`/
export DIR

cd $MYTMP

set -e

dl=https://launchpad.net/ubuntu/+archive/primary/+files/util-linux_2.27.1.orig.tar.xz

echo $dl
curl -s -L -o util-linux.tar.xz "$dl"

mkdir build
tar xfJC util-linux.tar.xz build

cd build/util-*
./configure --disable-all-programs --enable-unshare
make
make install
