#!/bin/sh

if [ ! -f .gitignore -o ! -f sbin/firehol.in ]
then
  echo "Run as ./packaging/dev-build from a firehol git repository"
  exit 1
fi

# If we are genuinely in a git repo, try to clean it up, otherwise
# just make the assumption
if [ -d .git ]
then
  if [ -n "$TRAVIS_TAG" ]
  then
    echo "Checking we have a good signature during CI build..."
    echo "Checking tag: $TRAVIS_TAG"
    git tag -v "$TRAVIS_TAG" 2>&1 | tee /tmp/tagcheck
    grep -iq "gpg. good signature" /tmp/tagcheck
    status=$?
    rm -f /tmp/tagcheck
    if [ $status -ne 0 ]
    then
      exit $status
    fi
  fi

  clean=$(git status -s | grep "^?")
fi

if [ "$clean" ]
then
  if [ "$1" != "-ok" ]
  then
    echo "Warning: this script runs: git clean -d -f -x"
    echo "         ensure all required ?? files are added, then re-run with '-ok'"
    git status -s | grep '^?'
    exit 1
  fi
fi

set -e

git clean -d -f -x
./autogen.sh
./configure --enable-maintainer-mode 
sed -i -e '1idevelopment' NEWS
set +e
make dist
status=$?
sed -i -e '1d' NEWS
exit $status
