#!/bin/sh

get_version() {
	if [ "$TRAVIS_TAG" ]
	then
		echo "$TRAVIS_TAG" | sed -e 's/^v//'
		return 0
	fi
	GIT_REF='$Format:%d,commit-%h$'
	local IFS=":(), "
	set -- "$GIT_REF"
	ver='$Id$'
	for i in $@
	do
		case "$i" in
			*[0-9].[0.9]*)
				echo "$i" | sed -e 's/^v//'
				return 0
			;;
			commit-[0-9a-zA-Z]*)
				ver="$i"
			;;
		esac
	done
	echo "$ver"
	return 0
}

version=`get_version | grep -v '^.Id:'`
if [ "$version" ]
then
	# SHA Id of packver will not help find a version of the scripts
	echo "$version" | tr -d "\n"
else
	echo "development"  | tr -d "\n"
fi
