#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If you want to allow non-ascii filenames set this variable to true.
allownonascii=$(git config hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ascii filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	echo "Error: Attempt to add a non-ascii file name."
	echo
	echo "This can cause problems if you want to work"
	echo "with people on other platforms."
	echo
	echo "To be portable it is advisable to rename the file ..."
	echo
	echo "If you know what you are doing you can disable this"
	echo "check using:"
	echo
	echo "  git config hooks.allownonascii true"
	echo
	exit 1
fi

git show :packaging/pre-commit > /tmp/staged-packaging-pre-commit$$
if ! cmp /tmp/staged-packaging-pre-commit$$ .git/hooks/pre-commit >/dev/null 2>&1
then
  status=1
  rm -f /tmp/staged-packaging-pre-commit$$
  echo "pre-commit differs between packaging and installed versions"
  echo ""
  echo "Bring them in line:"
  echo "  cp packaging/pre-commit .git/hooks/pre-commit"
  echo ""
  echo "Or, if you updated the .git version:"
  echo "  cp .git/hooks/pre-commit packaging/pre-commit"
  echo "  git add packaging/pre-commit"
  exit 1
fi

# Files we will check in their entirety
git show :ChangeLog > /tmp/staged-ChangeLog.$$
git show :NEWS > /tmp/staged-NEWS.$$
git show :sbin/firehol.in > /tmp/staged-sbin-firehol.in$$
git show :sbin/fireqos.in > /tmp/staged-sbin-fireqos.in$$
git show :sbin/link-balancer.in > /tmp/staged-sbin-link-balancer.in$$
git show :configure.ac > /tmp/staged-configure.ac$$

status=0

clogver=`sed -ne '1s/.*(\(.*\)).*/\1/p' /tmp/staged-ChangeLog.$$`
newsver=`head -n 10 /tmp/staged-NEWS.$$ | sed -ne 's/.*\<\([1-9][0-9]*\.[0-9][0-9]*[0-9A-Za-z.-]*\).*/\1/p' | head -n 1`

./packaging/check-log /tmp/staged-ChangeLog.$$
status=$?

if [ $status -eq 0 -a ! "$clogver" ]
then
  echo "Could not get version from ChangeLog"
  status=1
fi

if [ $status -eq 0 -a ! "$newsver" ]
then
  echo "Could not get version from NEWS"
  status=1
fi

if [ $status -eq 0 -a "$newsver" != "$clogver" ]
then
  echo "Version in NEWS ($newsver) differs from ChangeLog ($clogver)"
  status=1
fi

check_commands() {
  local status=0
  # Find commands that have been enclosed in quotes and remove anything after
  #  if nothing matched the substitution, proceed to the next line
  #  if the command is used in a -z check, proceed to the next line
  #  if the command is in posix size check [ "$var" ], proceed to the next line
  #  if the command is being assigned to a variable, proceed to the next line
  #  if the command is being used in an eval, proceed to the next line
  # Anything left, print the line number
  sed -n -e 's/\("\$[^"}]*_CMD}\).*/\1/' \
         -e T \
         -e '/-z *"\$/b' \
         -e '/\[ *"\$/b' \
         -e '/= *"\$/b' \
         -e '/eval *"\$/b' \
         -e '{=}' \
         /tmp/staged-sbin-${1}$$ > /tmp/staged-problem-lines.$$
  if [ -s /tmp/staged-problem-lines.$$ ]
  then
    status=1
    echo "Detected use(s) of '${SOMETHING_CMD}' in ${1}. Check lines:"
    cat /tmp/staged-problem-lines.$$
  fi

  # Ignore lines from the command table and require_cmd entries
  # ensure at least 2 characters before and after each word, reset cond jump
  # extract the command and immediate surroundings, got to next line if no match
  # remove brackets
  # proceed to next line if command starts with a dollar
  # proceed to next line if command ends with equals (assignment)
  # print line number
  sed -n -e '/^[YN]|/b' -e '/require_cmd/b' \
         -e 's/^/  /' -e 's/$/  /' -e T \
         -e 's/.*\(..\<[A-Z0-9_]*_CMD..\).*/\1/' -e T \
         -e 's/[{}]//' \
         -e '/$[A-Z]/b' \
         -e '/[A-Z0-9]=/b' \
         -e '=' \
         /tmp/staged-sbin-${1}$$ > /tmp/staged-problem-lines.$$
  if [ -s /tmp/staged-problem-lines.$$ ]
  then
    status=1
    echo "Detected use(s) of 'SOMETHING_CMD' (missing \$) in ${1}. Check lines:"
    cat /tmp/staged-problem-lines.$$
  fi

  grep "^[YN]|" /tmp/staged-sbin-${1}$$ > /tmp/staged-cmd.$$
  for cmd in $(tr " " "\n" < /tmp/staged-sbin-${1}$$ |
             sed -n -e 's/.*\(\<[A-Z0-9_]*\)_CMD.*/\1/p' | sort | uniq)
  do
    if ! grep -q "^[YN]|${cmd}_CMD|" /tmp/staged-cmd.$$
    then
      status=1
      echo "Missing definition of $cmd in $1 detection table."
    fi

    # Hostname is a special case - configure will expand it to running host,
    # overwriting the value we wanted to use.
    if [ "$cmd" = "HOSTNAME" ]; then cmd="HOSTNAMECMD"; fi
    if ! grep -q "_${cmd}(\|\[$cmd\]" /tmp/staged-configure.ac$$
    then
      status=1
      echo "Missing detection of $cmd for $1 in configure.ac"
    fi
  done

  return $status
}

check_commands firehol.in || status=1
check_commands fireqos.in || status=1
check_commands link-balancer.in || status=1

rm -f /tmp/staged-*.$$

if [ $status -ne 0 ]
then
  exit $status
fi

# If there are whitespace errors, print the offending file names and fail.
#exec git diff-index --check --cached $against --
